### BEGIN STRIPE
source ~/.profile
### END STRIPE

### BEGIN HENSON
export PATH="/Users/jez/stripe/henson/bin:$PATH"
### END HENSON

if [ -f "$HOME/.bashrc" ]; then
  source "$HOME/.bashrc"
fi

# START - Managed by chef cookbook stripe_cpe_bin
alias tc='/usr/local/stripe/bin/test_cookbook'
alias cz='/usr/local/stripe/bin/chef-zero'
alias cookit='tc && cz'
# STOP - Managed by chef cookbook stripe_cpe_bin
