colors:
  body: none
  date: none
  tags: none
  title: none
default_hour: 9
default_minute: 0
editor: nvim
encrypt: false
highlight: true
indent_character: '|'
journals:
  brag: /Users/jez/Dropbox/Stripe/notes/brag.txt
  default: /Users/jez/Dropbox/Stripe/notes/journal.txt
linewrap: false
tagsymbols: '#'
template: false
timeformat: '%Y-%m-%d %H:%M'
version: v4.2.1
