syn match sorbetStrictLevel  "\%#=1\<\%(ignore\|false\|true\|strict\|strong\|autogenerated\|__STDLIB_INTERNAL\)\>[?!]\@!"
syn match rubyMagicComment   "\c\%<10l#\s*\zs\(typed\):" contained nextgroup=sorbetStrictLevel  skipwhite
syn match rubyMagicComment   "\c\%<10l#\s*\zs\(compiled\):" contained nextgroup=rubyBoolean  skipwhite

hi def link sorbetStrictLevel Boolean
